config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :categories
  resources :banners
  resources :contacts, only: [:new, :create]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  resources :orders, except: [:edit, :update, :destroy]
  resources :checkouts, except: [:edit, :update, :destroy], param: :slug
  
  resources :pages, param: :slug do 
    collection { post :sort }
  end

  get 'all-banners', to: 'banners#display'
  post 'uploads' => 'uploads#create'

  root "banners#index"
  
  devise_for :users,
    path: "", 
    controllers: { 
      registrations: 'registrations', 
      :omniauth_callbacks => "users/omniauth_callbacks" 
    },
    path_names: { 
      sign_in: 'login', 
      password: 'forgot', 
      confirmation: 'confirm', 
      unlock: 'unlock', 
      sign_up: 'register', 
      sign_out: 'logout' 
    }
end

app/models/banner.rb
class Banner < ApplicationRecord
  has_many :pictures, as: :imageable, dependent: :delete_all
  belongs_to :user
  accepts_nested_attributes_for :pictures, allow_destroy: true

  validates :name, presence: true, length: { in: 2..30 }, format: { with: /\A[A-Za-z\s]+\z/ }

  def self.image_styles
    {
      original: "1000x",
      thumb: "300x300#",
    }
  end
end

app/controllers/banners_controller.rb
class BannersController < ApplicationController
	before_action :find_banner, only: [:show, :edit, :update, :destroy]
	before_action :authorize_admin, only: [:new, :create, :edit, :update, :destroy]

	def index
		@banner = Banner.all.order("created_at DESC")
	end

	def display
		@banner = Banner.all.order("created_at DESC")
	end

	def show; end

	def new
		@banner = current_user.banners.build
	end

	def create
		@banner = current_user.banners.build(banners_params)

		respond_to do |format|
			if @banner.save

				if params[:images]
					params[:images].each do |image|
						@banner.pictures.create(image: image, imageable_id: @banner.id)
					end
				end

				format.html { redirect_to @banner, notice: 'Banner was successfully created.' }
				format.json { render json: @banner, status: :created, location: @banner }
			else
				format.html { render action: "new" }
				format.json { render json: @banner.errors, status: :unprocessable_entity }
			end
		end
	end

	def edit
	end

	def update
		if @banner.update(banners_params)
			# Check if any new images have been added
			if params[:images]
				params[:images].each do |image|
					# Create the images
					@banner.pictures.create(image: image, imageable_id: @banner.id)
				end
			end
			redirect_to @banner
		else
			render "edit"
		end
	end

	def destroy
		@banner.destroy
		redirect_to root_path
	end

		private

	def banners_params
		params.require(:banner).permit(:name, :pictures, pictures_attributes: [:id, :image, :_destroy])
	end

	def find_banner
		@banner = Banner.find(params[:id])
	end
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/views/banners/_form.html.erb
<div class="center">
  <%= simple_form_for @banner, :html => { :multipart => true }, validate: true do |f| %>
  	<% if @banner.errors.full_messages.any? %>
  		<div class="error_notification">
  			<p>Error(s):</p>
			  <% @banner.errors.full_messages.each do |error_message| %>
			    	<p><%= error_message %></p>
			  <% end %>
			</div>
		<% end %>
   	<%= f.input :name %>
		<br>
		<%= f.label :pictures %>
		<div class="form-pictures">
	   	<% if @banner.pictures.count == 0 %>
	   		<%= file_field_tag "images[]", type: :file, multiple: true, accept:'image/*' %>
	   	<% else %>
				<%= f.simple_fields_for :pictures do |image| %>
					<div class="edit-pictures">
						<div class="pictures-edit-options">
							<div class="pictures-checkbox">
								<%= image.check_box :_destroy %>
				    		<%= image.label :_destroy, "Remove Image" %>
				    	</div>
							<%= image.label :image, "Replace Image" %>
							<br>
				    	<%= image.file_field :image, accept:'image/*' %>
				    </div>
				    <%= image_tag image.object.image.url(:thumb) %>
			    	<hr>
			    </div>
		    <% end %>
		    <span class="upload-more-images">Upload More Images</span>
		    <%= file_field_tag "images[]", type: :file, multiple: true, accept:'image/*' %>
	   	<% end %>
	   </div>
   
    <%= f.submit %>

  <% end %>
</div>

app/views/banners/display.html.erb
<div class="text-ceter categories">
  <h1 class="grid-title">Banners</h1>
  <div class="grid">
    <% @banner.each do |banner| %>
      <div class="grid-item">
        <% if banner.pictures.length != 0 %>
          <% banner.pictures.limit(1).each do |picture| %>
            <%= link_to image_tag(picture.image.url(:thumb)), banner, 'data-turbolinks' => false %>
          <% end %>
        <% else %>
          <%= link_to banner.name, banner %>
        <% end %>
        <span class="grid-caption"><%= banner.name %></span>
      </div>
    <% end %>
  </div>

  <br><br>
  <%= link_to "New Banner", new_banner_path, class: "custom-button" %>
</div>

app/views/banners/edit.html.erb
<div class="center">
	<h1>Edit Banner</h1>

	<%= render "form" %>
</div>

app/views/banners/index.html.erb
<% content_for(:body_attributes) do %>
  data-turbolinks="false"
<% end %>

<div class="image-gallery banner">
   <div>
    <% @banner.limit(1).each do |banner| %>
      <% banner.pictures.each do |picture| %>
        <%= image_tag(picture.image.url(:original), :class => "slider banner-slider") %>
      <% end %>
      <div id="previous"></div>
      <div id="next" class="next-banner"></div>
      <div class="image-gallery-links banner-image-gallery-links">
        <% banner.pictures.each_with_index do |picture, index| %> 
          <a href="<%= index + 1 %>"><%= index + 1 %></a>
        <% end %>
      </div>
    <% end %>
   </div>
</div>

<div class="categories home-categories">
  <h1 class="grid-title">Product Categories</h1>
  <div class="grid">
    <% Category.all.each do |category| %>
      <div class="grid-item">
        <%= link_to image_tag(category.image.url), products_path(category: category.name) %>
        <span class="grid-caption"><%= category.name %></span>
      </div>
    <% end %>
  </div>
</div>

app/views/banners/new.html.erb
<div class="center">
	<h1>New Banner</h1>

	<%= render "form" %>
</div>

app/views/banners/show.html.erb
<div class="center">
  <h1 class="grid-title">Preview</h1>
</div>

<div class="image-gallery banner banner-show">
   <div>
      <% @banner.pictures.each do |picture| %>  
        <%= image_tag(picture.image.url(:original), :class => "slider banner-slider") %>
      <% end %>
      <div id="previous"></div>
      <div id="next" class="next-banner"></div>
      <div class="image-gallery-links banner-image-gallery-links <%= @banner.pictures.count == 1 ? 'banner-links-hidden' : '' %>">
        <% @banner.pictures.each_with_index do |picture, index| %> 
          <a href="<%= index + 1 %>"><%= index + 1 %></a>
        <% end %>
     </div>
   </div>
</div>
<br>
<div class="text-center">
  <%= link_to "Edit banner", edit_banner_path(@banner), class: "custom-button" %>
  <%= link_to "Delete banner", banner_path(@banner), method: :delete, data: {confirm: "Are you sure?"}, class: "custom-button" %>
</div>