config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :categories
  resources :banners
  resources :contacts, only: [:new, :create]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  resources :orders, except: [:edit, :update, :destroy]
  resources :checkouts, except: [:edit, :update, :destroy], param: :slug
  
  resources :pages, param: :slug do 
    collection { post :sort }
  end

  get 'all-banners', to: 'banners#display'
  post 'uploads' => 'uploads#create'

  root "banners#index"
  
  devise_for :users,
    path: "", 
    controllers: { 
      registrations: 'registrations', 
      :omniauth_callbacks => "users/omniauth_callbacks" 
    },
    path_names: { 
      sign_in: 'login', 
      password: 'forgot', 
      confirmation: 'confirm', 
      unlock: 'unlock', 
      sign_up: 'register', 
      sign_out: 'logout' 
    }
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
    @order = current_order
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart_row.html.erb
<div class="cart-row">
  <%= link_to image_tag("remove.png", class: "remove-item", title: "Remove item"), order_item, { data: { confirm: "Are you sure you wish to delete the product '#{order_item.product.name}' from your cart?" }, method: :delete, remote: true } %>
  <div class="content">
    <div class="product-image">
      <% product.pictures.limit(1).each do |picture| %>
        <%= link_to image_tag(picture.image.url(:grid)), product, 'data-turbolinks' => false %>
      <% end %>
    </div>
  
    <div class="cart-product-details">
      <h3><%= product.name %></h3>
      <p><%= order_item.quantity %> x <%= number_to_currency order_item.unit_price %></p>
    </div>

    <div class="form">
      <%= form_for order_item, remote: true, :html => { id: "update-quantity-form" } do |f| %>
        <div class="right">

          <%= f.select :quantity, (1..product.quantity), {}, value: order_item.quantity.to_i, class: "quantity-input" %>
          <div class="order-item-total">
            <%= number_to_currency order_item.total_price %>
          </div>
          <%= f.hidden_field :product_id, value: product.id %>
          <div class="update-quantity">
            <%= link_to "Update Quantity", "", :onclick => "$('#update-quantity-form').submit()", class: "custom-button text-sm" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @order_items.size == 0 %>
  <div class="center text-center">
    <p>There aren't any items in your shopping cart.</p>  
    <p>Please <%= link_to "go back", products_path %> and add some items to your cart.</p>
  </div>
<% else %>
  <div class="cart">
    <h2>Shopping Cart</h2>
    <p>You have <b><%= current_order.order_items.size > 1 ? current_order.order_items.size.to_s + " items" : current_order.order_items.size.to_s + " item" %></b> in your shopping cart</p>
    
    <div class="cart-row-border">
      <% @order_items.each do |order_item| %>
        <%= render 'carts/cart_row', product: order_item.product, order_item: order_item, show_total: true %>
      <% end %>
    </div>

    <div class="cart-finish">
      <h3 class="cart-total">Total: <%= number_to_currency @order.subtotal %></h3>
      <%= link_to "Checkout Now", new_checkout_path(order_id: @order.id), class: "custom-button" %>
    </div>
  </div>
<% end %>

app/views/carts/show.html.erb
<div class="shopping-cart center">
  <%= render "shopping_cart" %>
</div>