config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :categories
  resources :banners
  resources :contacts, only: [:new, :create]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  resources :orders, except: [:edit, :update, :destroy]
  resources :checkouts, except: [:edit, :update, :destroy], param: :slug
  
  resources :pages, param: :slug do 
    collection { post :sort }
  end

  get 'all-banners', to: 'banners#display'
  post 'uploads' => 'uploads#create'

  root "banners#index"
  
  devise_for :users,
    path: "", 
    controllers: { 
      registrations: 'registrations', 
      :omniauth_callbacks => "users/omniauth_callbacks" 
    },
    path_names: { 
      sign_in: 'login', 
      password: 'forgot', 
      confirmation: 'confirm', 
      unlock: 'unlock', 
      sign_up: 'register', 
      sign_out: 'logout' 
    }
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products
	belongs_to :user

	validates :name, presence: true, length: { in: 2..30 }, format: { with: /\A[A-Za-z\s]+\z/ }

  has_attached_file :image, 
    styles: { 
      original: "300x" 
    }, 
    :url => "/pictures/categories/:id/:style/:filename", 
    :path => ":rails_root/public/pictures/categories/:id/:style/:filename",
    :convert_options => {
      :original => "-strip",
    },
    default_url: "/images/missing.png"
  
  validates_attachment :image, 
    presence: true,
    content_type: { 
      content_type: ["image/jpeg", "image/jpg", "image/png"] 
    }, 
    if: Proc.new {|a| a.image.present? }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :find_category, only: [:edit, :update, :destroy]
	before_action :authorize_admin

	def index
		@category = Category.all.order('created_at ASC')
	end

	def new
		@category = current_user.categories.build
	end

	def create
		@category = current_user.categories.build(categories_params)

		if @category.save
			redirect_to categories_path
		else
			render 'New'
		end
	end

	def edit; end

	def update
		if @category.update(categories_params)
			redirect_to categories_path
		else
			render 'Edit'
		end
	end

	def destroy
		@category.destroy
		redirect_to categories_path
	end

		private

	def categories_params
		params.require(:category).permit(:name, :image, :user_id)
	end

	def find_category
		@category = Category.find(params[:id])
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="center">
	<%= simple_form_for @category, :html => { :multipart => true }, validate: true do |f| %>
	    <%= f.input :name %>
      <%= f.input :image, as: :file %>
	    <%= f.submit %>
	<% end %>
</div>

app/views/categories/edit.html.erb
<div class="center">
	<h1>Edit Category</h1>

	<%= render "form" %>
	<%= link_to "Delete", @category, method: :delete, data: {confirm: "Are you sure?"} %>
</div>

app/views/categories/index.html.erb
<div class="text-center">
  <div class="categories">
    <h1 class="grid-title">All Categories</h1>
    <div class="grid">
      <% Category.all.each do |category| %>
        <div class="grid-item">
          <%= link_to image_tag(category.image.url), products_path(category: category.name) %>
          <span class="grid-caption"><%= category.name %></span>
        </div>
      <% end %>
    </div>
  </div>
  
  <br><br>
  <%= link_to "New Category", new_category_path, class: "custom-button" %>
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render "form" %>